### ISSUE TITLE
Conversation Error with Push Notification in PrivacyIdea 3.0

### ISSUE THREAD

**Issue by bryannorton** [privacyidea/pam_python#8]
With the recent update to PrivacyIdea, I'm attempting to get the Push Notification working.  It might not be possible to use this with PAM, but I'm posting here just in case it's something simple.  The client server works fine using a TOTP token, but when a user is configured for a Push token, the notification is sent to the user's phone, however the client server login prompt issues a "access denied" error almost immediately.  The error in /var/log/messages states:

*Edit* Removed the error since @spaceone cleaned it up and made it look much more readable

**Comment by spaceone** [comment]
```
Traceback (most recent call last):
 File "/usr/lib64/security/privacyidea_pam.py", line 329, in pam_sm_authenticate
    rval = Auth.authenticate(pamh.authtok)
 File "/usr/lib64/security/privacyidea_pam.py", line 196, in authenticate
    attributes)
 File "/usr/lib64/security/privacyidea_pam.py", line 211, in challenge_response
    response = self.pamh.conversation(pam_message)
PamException: Conversation error
```

**Comment by plettich** [comment]
Thanks for the report.
The privacyIDEA-PAM module is not yet ready for the push token.
We need to poll the server to check if the push authentication was successful.

**Comment by cornelinux** [comment]
So to my understanding we turn this into a feature request so that this module will support push.

**Comment by cornelinux** [comment]
I opened a [new issue](https://github.com/privacyidea/pam_python/issues/9) and take the liberty of closing this very issue.
